name: ld30
description: A sample dartemis application
dependencies:
  a_star: any
  browser: any
  canvas_query: any
  dart_to_js_script_rewriter: any
  gamedev_helpers:
    path: ../gamedev_helpers
  dartemis: any
  dartemis_transformer: any
transformers:
- dart_to_js_script_rewriter
- dartemis_transformer:
    additionalLibraries:
    - gamedev_helpers/gamedev_helpers.dart